### ISSUE TITLE
Verse Developer extension doesn't work and my mail is on https://mail.notes.ce.collabserv.com/verse

### ISSUE THREAD

**Issue by markewallace** [ibmcnxdev/verse-developer-chrome-ext#1]
If you have set up the Verse Developer Chrome extension and it doesn't work it may be that you have an older cached version of the Verse application files. Try opening a New Incognito Window and try to the the Verse developer extension from there. If that works then the next time you log in from the normal window the issue should be resolved

**Comment by jjtbsomhorst** [comment]
Thanks for looking into this. I just resolved my issue with the above fix.
