### ISSUE TITLE
https://ibmcnxdev.github.io/verse-developer-chrome-ext/samples should be used instead of https://git.swg.usma.ibm.com ...

### ISSUE THREAD

**Issue by BerndGewehr** [ibmcnxdev/verse-developer-chrome-ext#2]
Hi!

The docs lead to a target that seems to be no longer available:

https://git.swg.usma.ibm.com/pages/IBM-Verse/verse-developer-chrome-ext/samples/actions.html

**Comment by BerndGewehr** [comment]
It's hard to find the sample html files when you did not understand that they are in the other branch.. 

Maybe they coul be in the master branch too - just for simplicity reasons.

**Comment by markewallace** [comment]
@BerndGewehr good point, we will make this change
