### ISSUE TITLE
Can you guide me to a productive implementation?

### ISSUE THREAD

**Issue by BerndGewehr** [ibmcnxdev/verse-developer-chrome-ext#3]
What if the development is done and we want to deploy a feature to our users?

How should we do that? Is there a guideline od some docs too?

**Comment by BerndGewehr** [comment]
Well, I think I got it.

https://chrome.google.com/webstore/detail/v%C3%B6ssing-extension-for-ibm/bdlikjejidmknhiejmnklgknpbgbdiei?hl=de

**Comment by markewallace** [comment]
@BerndGewehr you can use the Application Registry to deploy your application for a customer. There is no need to deploy a Chrome extension. The Chrome extension is only needed during development.

**Comment by BerndGewehr** [comment]
Well, in that case I did not understand the process of extension deployment. Could you point it out in detail?

**Comment by BerndGewehr** [comment]
Ah, I found the CNX cloud app registry has a new extension point "Verse". But how to use that? Where is the docs?

**Comment by markewallace** [comment]
Here's a link to the documentation: https://www-10.lotus.com/ldd/appdevwiki.nsf/xpDocViewer.xsp?lookupName=Dev+Guide+topics#action=openDocument&res_title=Managing_organization_extensions&content=sdkcontent

**Comment by BerndGewehr** [comment]
Well, that's a well knwon page but it does not say a word about using the verse extension point? Or am i too stupid to see it?

**Comment by markewallace** [comment]
@BerndGewehr the documentation is being updated at the moment, I'll pass on your comments to the documentation team.

**Comment by BerndGewehr** [comment]
Thank you Mark! So I will have to wait?

**Comment by markewallace** [comment]
@BerndGewehr if there is something you need to get done soon I can connect with with someone on the application registry team

**Comment by BerndGewehr** [comment]
Well - I really would appreciate that! THX!

**Comment by BerndGewehr** [comment]
One simple help please: what to put into the ID field of the org extension dialog for verse extensions?

**Comment by BerndGewehr** [comment]
I played around with the org extensions settings for a while. Man it's not only the docs that are bad, the whole thing is buggy as hell. Please care!

**Comment by markewallace** [comment]
@BerndGewehr I will follow up with the application registry team tomorrow

**Comment by maire-kehoe** [comment]
@BerndGewehr  Hi. I'm one of the developers on the application registry team. Sorry to hear that you're experiencing problems - please let us know of any specific issues. 

About your question:
>  what to put into the ID field of the org extension dialog for verse extensions?

It is expected to contain a value like com.myCompany.bizcard.button, which can be used to programmatically identify the extension. The value must be unique - duplicate extension IDs under other applications are not allowed. 

That ID field in the dialog is saved in the JSON as "ext_id". There is a separate auto-generated "id" field containing a UUID value, like: "id": "fc4682ff-daf5-4305-9533-d4e0bcd8bf68", but you do not need to specify that field value, as the value will be generated by the server.

**Comment by BerndGewehr** [comment]
@maire-kehoe could you please provide working example app registry Jsons for the samples of this repo? I had no luck in using the provided ones or in creating my own.

**Comment by mangelcalvo** [comment]
@maire-kehoe Hi. It seems that the App Registry is not yet ready for Verse despite the dropdown "Service" menu includes the "Verse" option. If not, it would be quite useful if you could provide a visual example of how to fill up the app registry form. Thanks.

**Comment by maire-kehoe** [comment]
@BerndGewehr, @mangelcalvo 
To change the samples in this repo from the chrome extension syntax to the AppRegistry syntax,
mostly you need to convert id fields to app_id and ext_id fields,
to remove the outer [ ] array, and where the file has multiple applications,
to split it so that each application is uploaded separately.

So, for example, the first application in:
[/tutorial/step3/applications.json](https://github.com/ibmcnxdev/verse-developer-chrome-ext/blob/master/tutorial/step3/applications.json)

would be uploaded to the AppRegistry as a file with contents:

      {
        "app_id": "com.ibm.verse.sample.app.templatedlink",
        "name": "Person Sample",
        "title": "Templated Link Person Sample",
        "description": "This samples demonstrates using the Templated Link extension point with a Person object",
        "extensions": [
          {
            "ext_id": "com.ibm.verse.sample.ext.templatedlink",
            "name": "Person Templated Link",
            "type": "com.ibm.appreg.ext.templatedLink",
            "object": "com.ibm.appreg.object.person",
            "payload": {
              "text": "Person Action",
              "title": "Person Action",
              "href": "https://ibmcnxdev.github.io/verse-developer-chrome-ext/samples/templatedLink.html?searchFor=${profile.primaryEmail}"
            }
          }
        ],
        "services": [
          "Verse"
        ]
      }

**Comment by BerndGewehr** [comment]
Yes, that works well @maire-kehoe ! Great! Can you achieve the same result by adding the extensions via the current form?
![2017-01-16 13_28_39-organization extensions](https://cloud.githubusercontent.com/assets/21081707/21983107/beb4bfa0-dbef-11e6-857a-80022cb59a55.png)

Is it only one extension per app?

**Comment by BerndGewehr** [comment]
When editing the Verse extension, you edit in a json line editor. Why not use the forms?
![2017-01-16 13_30_37-organization extensions](https://cloud.githubusercontent.com/assets/21081707/21983149/04ae0d68-dbf0-11e6-9728-c3adcc09a7c0.png)

**Comment by maire-kehoe** [comment]
@BerndGewehr The UI does not currently allow editing the applications and extensions through the forms; that request has been logged as OCS#211765. 
You can create multiple extensions per application.
Yes, it is possible to add/create the applications and extensions through the forms instead of uploading as files. 
Some of the fields names in the JSON / English / German have slightly unusual labels:

- "payload": / Properties: / Eigenschaften:
- "type": / Extension Point: / Erweiterungspunkt:

**Comment by BerndGewehr** [comment]
OK, got it.

Here another example of a working extension (downloaded from the app registry):

````
{
  "extensions": [
    {
      "applications": [
        "Mail Compose Action Name"
      ],
      "ext_id": "com.ibm.verse.sample.ext.widget.mail.actions",
      "type": "com.ibm.verse.ext.widget",
      "name": "Mail Actions Extension name",
      "id": "3b6e4a52-d190-4938-b3e5-8f2c12f43aca",
      "payload": {
        "features": [
          "core"
        ],
        "actions": [
          {
            "path": "mail.compose",
            "location": "window",
            "title": "Mail Compose Action",
            "id": "com.ibm.verse.ext.mail.compose.action",
            "renderParams": {
              "width": "900",
              "height": "500"
            },
            "text": "Mail Compose Action"
          }
        ],
        "url": "https://ibmcnxdev.github.io/verse-developer-chrome-ext/samples/actions.html"
      }
    }
  ],
  "title": "Mail Compose Action Title",
  "app_id": "com.ibm.verse.sample.app.widget.mail.actions",
  "name": "Mail Compose Action Name",
  "id": "e9ace498-d4e4-4e73-b5be-864d2790c999",
  "description": "Mail Sample Description",
  "services": [
    "Verse"
  ]
}
````

**Comment by BerndGewehr** [comment]
@maire-kehoe 
- when will the documentation be available?
- when will the errors in OCS#211765 be fixed?

**Comment by DanieleVistalli** [comment]
Bernd, seems some docs is coming: https://www-10.lotus.com/ldd/appdevwiki.nsf/xpDocViewer.xsp?lookupName=Dev+Guide+topics#action=openDocument&res_title=Managing_applications_for_Verse_or_the_Top_Navigation_Bar&content=sdkcontent

Now I want to learn about "Top navigation bar extensibility" that's also part of Verse app-registry.

**Comment by BerndGewehr** [comment]
Yes we're waiting for that one, too.

Did you understand how Verse extensions should be combined with others in that multiselection thing of services? Any known examples for that?

If you ask me these things should be much better documented and described with examples and references. I saw ionic.io docs as a bright example how really good docs can look like. IBM can improve so much about docs and helping the Dev community... hope they'll do!

**Comment by DanieleVistalli** [comment]
As far as I know there are no significant samples available... we all look forward to it.

**Comment by mangelcalvo** [comment]
@maire-kehoe Is the sample #3:#3 (comment) still valid ? I need to include a random id

```
"app_id": "com.ibm.verse.sample.app.templatedlink",
"id": "e9ace498-d4e4-4e73-b5be-864d2790c888",
"name": "Person Sample",
```

if I want to add my extension. Later the system changes the id.

**Comment by maire-kehoe** [comment]
@mangelcalvo Yes, the [comment](https://github.com/ibmcnxdev/verse-developer-chrome-ext/issues/3#issuecomment-272845645) is still valid. 
When registering an extension using the Chrome browser extension you need to provide an "id" field, and it usually has a reverse-domain-name syntax (like "com.example.something").
When registering an extension using the AppRegistry a.k.a. the Admin, Organization Extensions page, 
you need to provide an "app_id" field, and it is usually in reverse-domain-name format. For the AppRegistry, you don't need to provide an "id" - if you do provide a "id" field in uuid-format, that "id" will be used, else if the "id" is absent a new random "id" will be generated automatically.

**Comment by mangelcalvo** [comment]
@maire-kehoe Thank you

**Comment by BerndGewehr** [comment]
@andrehagemeier have a look at this to see the state of how the appregistry docs help us or not.

**Comment by BerndGewehr** [comment]
Well I would like you to see proving the docs by taking a well educated newbie and tell him he should use them to build valid extensions. If he should fail again and again, then the docs are not enough. If not, I'm much dumber than I thought. So all issues had the same conclusion: errourness app registry and bad docs don't make the customer happy. Hope that these things improve over time.
