### ISSUE TITLE
Chrome packed apps no longer available for non chrome-OS users?

### ISSUE THREAD

**Issue by BerndGewehr** [ibmcnxdev/verse-developer-chrome-ext#4]
following this:
https://blog.chromium.org/2016/08/from-chrome-apps-to-web.html

I read
"As we continue our efforts to simplify Chrome, we believe it’s time to begin the evolution away from the Chrome apps platform. There are two types of Chrome apps: packaged apps and hosted apps. Today, approximately 1% of users on Windows, Mac and Linux actively use Chrome packaged apps, and most hosted apps are already implemented as regular web apps. **We will be removing support for packaged and hosted apps from Chrome on Windows, Mac, and Linux over the next two years**"

How does that fit to the announcement of chrome extension for IBM Verse?
Should we really invest in this dead end?

**Comment by BerndGewehr** [comment]
I guess Chrome apps and Chrome extensions are not all the same, right? Sorry for being a beginner in the chrome area.

**Comment by markewallace** [comment]
@BerndGewehr so this Chrome extension is just a tool for developers to get their extension registered during development.

**Comment by BerndGewehr** [comment]
OK, got it.
