### ISSUE TITLE
Now that the TopMenuBar is accessible by using applications in org extensions please give examples how to use that

### ISSUE THREAD

**Issue by BerndGewehr** [ibmcnxdev/verse-developer-chrome-ext#6]
If you want to hide the org name menu at the leftmost position, you will have to use something like 

````
{
  "extensions": [
    {
      "applications": [
        "topMenuMod"
      ],
      "path": "com.ibm.navbar.order.1500",
      "title": "delete OrgMenuItem",
      "ext_id": "com.example.menubar.noorg",
      "type": "com.ibm.action.delete",
      "name": "delete OrgMenuItem",
      "id": "0c589b75-0e60-4273-b3b5-24ab72dbc65c"
    }
  ],
  "title": "topMenuMod",
  "icon": "",
  "app_id": "com.example.topMenuMod",
  "name": "topMenuMod",
  "id": "a1737842-6b3a-487b-9931-e456fbe07870",
  "services": [
    "TopNavigationBar"
  ],
  "url": ""
}
````

but how exactly can you address the existing menu items for deletion? Please help!!

**Comment by markewallace** [comment]
Hi Bernd, I have requested samples, will post as soon as I have them available

**Comment by BerndGewehr** [comment]
Look here for Danieles example.

It shows some magic secrets that need to be completed "A._org"...

**Comment by BerndGewehr** [comment]
https://github.com/Factor-y/ConnectionsCloudHowTo

**Comment by BerndGewehr** [comment]
@markewallace no examples yet? We're over a month in production now. What can we do to speed that up?

**Comment by markewallace** [comment]
@BerndGewehr there are examples of how to use the extension points, see the tutorials here: https://ibmverse.github.io/verse-developer/

Is this what you are looking for?

**Comment by markewallace** [comment]
@BerndGewehr I've contacted the team lead and asked him to respond to this query. This repo is for Verse specific extensions.

**Comment by artcorl** [comment]
Navbar extensions are documented in this wiki:

https://www-10.lotus.com/ldd/appdevwiki.nsf/xpDocViewer.xsp?lookupName=Dev+Guide+topics#action=openDocument&res_title=Managing_applications_for_Verse_or_the_Top_Navigation_Bar&content=sdkcontent

**Comment by artcorl** [comment]
Existing menu item deletion example. 

key points:
1. type=com.ibm.action.delete
2. path=dom node class name (e.g. .org)
3. service=TopNavigationBar

````
{
  "extensions": [
    {
      "path": ".org",
      "ext_id": "art.disableorgname",
      "name": "disable org name",
      "id": "720ffe22-75f2-4cc8-b743-c1609169bf33",
      "type": "com.ibm.action.delete",
      "title": "disable org name",
      "object": "",
      "applications": [
        "orgname"
      ]
    }
  ],
  "icon": "",
  "name": "orgname",
  "entitlement": "",
  "services": [
    "TopNavigationBar"
  ],
  "id": "bc69cc7f-2cf6-4a1c-854a-7063d15799d9",
  "title": "orgname",
  "app_id": "art.orgname",
  "url": ""
}
````

**Comment by markewallace** [comment]
Thanks @artcorl

**Comment by BerndGewehr** [comment]
Thank you all for caring. It may have confused me a little what this repo is intended for. As far as I am concerned the docs do help me a little but they do not make it easy to succeed in these tasks. Now that I'm done with my current wishes to change our header, I'm ok to close the issue. Maybe the docs improve over time and make it easier then to make brilliant org extensions. Again, thank you all.

**Comment by artcorl** [comment]
we'll use your feedback to help improve the docs. thanks for your input and understanding!
