### ISSUE TITLE
Failed to execute 'postMessage' on 'DOMWindow'

### ISSUE THREAD

**Issue by mangelcalvo** [ibmcnxdev/verse-developer-chrome-ext#7]
Hello,
    I tested the Extensions by following the tutorials and I was able to deploy an example in production. But right now, that example is not working any more and I'm getting the next message either using Chrome or Firefox when clicking on the extension link:
 
"Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://www.ittaka.com') does not match the recipient window's origin ('https://mail.notes.ce.collabserv.com')"

Any clue which can be the problem ?

Thanks in advance.

Miguel

[extensionSampleIttaka.txt](https://github.com/ibmcnxdev/verse-developer-chrome-ext/files/873078/extensionSampleIttaka.txt)

**Comment by mangelcalvo** [comment]
There was a problem in the remote URL being executed, that generated this cryptic message. Solved now.

**Comment by markewallace** [comment]
@mangelcalvo I'll create an internal defect for this to see can we generate a better error message in future. Just to clarify the URL to your extension was broken, was that the root cause?

**Comment by mangelcalvo** [comment]
@markewallace No, the problem was in the app being invoked. It was our fault. 
Thanks.
